# Generated by Django 4.2.11 on 2024-05-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_commit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commit',
            new_name='Comment',
        ),
    ]
