# Generated by Django 4.2.11 on 2024-05-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_commit_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='update',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default=int),
            preserve_default=False,
        ),
    ]
